# Wayland identity
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

# Toolkits
env = GDK_BACKEND,wayland,x11,*
env = SDL_VIDEODRIVER,wayland
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_QPA_PLATFORMTHEME,qt5ct:qt6ct
env = MOZ_ENABLE_WAYLAND,1
env = OZONE_PLATFORM,wayland
env = ELECTRON_OZONE_PLATFORM_HINT,auto

# Cursor
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

# Other varialbes:
# env = CLUTTER_BACKEND,wayland
# env = GSK_RENDERER,gl

xwayland {
  force_zero_scaling = true
}

cursor {
	no_hardware_cursors = true
	enable_hyprcursor = true
	sync_gsettings_theme = true
}

ecosystem {
    no_update_news = true
    no_donation_nag = true
}
