# Configure your keyboard/mouse/other input devices

input {
    kb_layout = no
		# kb_options = caps:swapescape
    kb_variant = nodeadkeys
    kb_model =
    kb_rules =

    follow_mouse = 1

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
		accel_profile = flat

    touchpad {
        natural_scroll = false
    }
}

gestures {
    workspace_swipe_distance = 700
    workspace_swipe_invert = false
    gesture = 3, horizontal, workspace
}
