# vim:ft=kitty
## name: Gotham

background #0c1014
foreground #d3ebe9

selection_background #091f2e
selection_foreground #99d1ce

url_color #599cab

# normal
color0  #0c1014
color1  #c23127
color2  #2aa889
color3  #edb443
color4  #599cdb
color5  #4e5166
color6  #33859E
color7  #99d1ce

# bright
color8  #11151c
color9  #c23127
color10 #2aa889
color11 #d26937
color12 #599cab
color13 #888ca6
color14 #99d1ce
color15 #d3ebe9
