# Gotham (Hyprland)
$base           = rgba(0c1014ff)
$surface        = rgba(11151cff)
$overlay        = rgba(091f2eff)

$muted          = rgba(4e5166ff)
$subtle         = rgba(1a3d48ff)
$text           = rgba(d3ebe9ff)

$accent         = rgba(2aa889ff)

$red            = rgba(c23127ff)
$green          = rgba(2aa889ff)
$yellow         = rgba(edb443ff)
$orange         = rgba(d26937ff)
$blue           = rgba(599cabff)
$magenta        = rgba(888ca6ff)
$cyan           = rgba(33859Eff)

$highlight_low  = rgba(11151cff)
$highlight_med  = rgba(091f2eff)
$highlight_high = rgba(0a3749ff)

$border         = rgba(0a3749ff)

$selection_bg   = rgba(0a3749ff)
$selection_fg   = rgba(d3ebe9ff)
