# Gotham
set -g @base            "#0c1014"
set -g @surface         "#11151c"
set -g @overlay         "#091f2e"

set -g @muted           "#4e5166"
set -g @subtle          "#1a3d48"
set -g @text            "#d3ebe9"

set -g @accent          "#2aa889"

set -g @red             "#c23127"
set -g @green           "#2aa889"
set -g @yellow          "#edb443"
set -g @orange          "#d26937"
set -g @blue            "#599cab"
set -g @magenta         "#888ca6"
set -g @cyan            "#33859E"

set -g @highlight_low   "#11151c"
set -g @highlight_med   "#091f2e"
set -g @highlight_high  "#0a3749"

set -g @border          "#0a3749"

set -g @selection_bg    "#0a3749"
set -g @selection_fg    "#d3ebe9"
