# vim:ft=kitty
## name: Deep Forest (dark green UI + muted everforest accents)

background #06110b
foreground #d3c6aa

selection_background #12261a
selection_foreground #d3c6aa

url_color #6fa9a2

active_border_color #8fb57a
inactive_border_color #0c1b12
bell_border_color #d96f72
visual_bell_color none

active_tab_background #0c1b12
active_tab_foreground #d3c6aa
inactive_tab_background #06110b
inactive_tab_foreground #7c827a
tab_bar_background #06110b

# black
color0  #0c1b12
color8  #7c827a

# red
color1  #d96f72
color9  #e07a7d

# green
color2  #8fb57a
color10 #99c185

# yellow
color3  #c7a96f
color11 #d2b679

# blue
color4  #6fa9a2
color12 #79b5ae

# magenta
color5  #c68dac
color13 #d09bb7

# cyan
color6  #76ad86
color14 #82b995

# white
color7  #b6ab93
color15 #d3c6aa
