# Deep Forest
$base           = 0xff06110b
$surface        = 0xff0c1b12
$overlay        = 0xff12261a
$muted          = 0xff7c827a
$subtle         = 0xffb6ab93
$text           = 0xffd3c6aa
$accent         = 0xff8fb57a
$red            = 0xffd96f72
$green          = 0xff8fb57a
$yellow         = 0xffc7a96f
$blue           = 0xff6fa9a2
$magenta        = 0xffc68dac
$cyan           = 0xff76ad86
$orange         = 0xffd08869
$highlight_low  = 0xff0c1b12
$highlight_med  = 0xff12261a
$highlight_high = 0xff183222
$border         = 0xff1b3a27
$selection_bg   = 0xff12261a
$selection_fg   = 0xffd3c6aa
