# Float and center settings and previews
windowrule = match:class ^(org\.pulseaudio\.pavucontrol|org\.gnome\.NautilusPreviewer|floatnmtui)$, float on
windowrule = match:class ^(org\.pulseaudio\.pavucontrol|org\.gnome\.NautilusPreviewer|floatnmtui)$, size 800 600

windowrule = match:class ^showmethekey-gtk$, float on
windowrule = match:class ^showmethekey-gtk$, size 2518 60

# Automatically follow newly created windows

# Firefox app windowrules
# windowrule = match:class ^firefox$, fullscreen_state 0 2
# windowrule = match:class ^firefox$, decorate off

# Rofi config
# layerrule = blur on, match:namespace rofi    # blur only the non-transparent bits
# layerrule = xray 1, match:namespace rofi
# layerrule = dim_around on, match:namespace rofi
# layerrule = animation popin 75%, match:namespace rofi

# Swaync config
layerrule = blur on, match:namespace swaync-notification-window
layerrule = ignore_alpha 0, match:namespace swaync-notification-window
layerrule = ignore_alpha 0, match:namespace swaync-control-center
layerrule = blur on, match:namespace swaync-control-center

# Workspace 4
windowrule = match:class ^discord$, workspace 4 silent
windowrule = match:class ^Spotify$, workspace 4 silent

# Workspace 5
windowrule = match:class ^pcsx2-qt$, workspace 5

# Ignore maximize requests from apps. You'll probably like this.
windowrule = match:class .*, suppress_event maximize

# Kitty opacity
windowrule = match:class ^kitty$, opacity 0.95 0.95
# windowrule = match:class ^kitty$, no_blur on

# Floating kitty terminal
windowrule = match:class ^kitty-float$, float on
windowrule = match:class ^kitty-float$, size (monitor_w*0.45) (monitor_h*0.60)
windowrule = match:class ^kitty-float$, center on

# Fix some dragging issues with XWayland
windowrule = match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0, no_focus on

# Example special workspace (scratchpad)
# bind = $mainMod, W, togglespecialworkspace, magic
# bind = $mainMod SHIFT, W, movetoworkspace, special:magic1
