# Cyberpunk
# Hyprland expects rgba(RRGGBBAA) without '#'

$base           = rgba(0a0b10ff)
$surface        = rgba(101116ff)
$overlay        = rgba(120b10ff)

$muted          = rgba(777777ff)
$subtle         = rgba(eeffffff)
$text           = rgba(eeffffff)

$accent         = rgba(ff0055ff)

$red            = rgba(ff0055ff)
$green          = rgba(00ff9cff)
$yellow         = rgba(fffc58ff)
$blue           = rgba(76c1ffff)
$magenta        = rgba(d57bffff)
$cyan           = rgba(00ffc8ff)
$orange         = rgba(ff4081ff)

$highlight_low  = rgba(101116ff)
$highlight_med  = rgba(120b10ff)
$highlight_high = rgba(1a1320ff)

$border         = rgba(777777ff)

$selection_bg   = rgba(120b10ff)
$selection_fg   = rgba(eeffffff)

$url            = rgba(fffc58ff)
