# Cyberpunk — standard role names

set -g @base            "#0A0B10"
set -g @surface         "#101116"
set -g @overlay         "#120B10"

set -g @muted           "#777777"
set -g @subtle          "#EEFFFF"
set -g @text            "#EEFFFF"

set -g @accent          "#FF0055"

set -g @red             "#FF0055"
set -g @green           "#00FF9C"
set -g @yellow          "#FFFC58"
set -g @blue            "#76C1FF"
set -g @magenta         "#D57BFF"
set -g @cyan            "#00FFC8"
set -g @orange          "#FF4081"

set -g @highlight_low   "#101116"
set -g @highlight_med   "#120B10"
set -g @highlight_high  "#1A1320"

set -g @border          "#777777"

set -g @selection_bg    "#120B10"
set -g @selection_fg    "#EEFFFF"

set -g @url             "#FFFC58"
