# Adwaita darker (Hyprland)
$base           = rgba(000000ff)
$surface        = rgba(101010ff)
$overlay        = rgba(1c1c1cff)

$muted          = rgba(9a9996ff)
$subtle         = rgba(c0bfbcff)
$text           = rgba(dedddaff)

$accent         = rgba(62a0eaff)

$red            = rgba(ed333bff)
$green          = rgba(57e389ff)
$orange         = rgba(ff7800ff)
$yellow         = rgba(ffa348ff)
$blue           = rgba(62a0eaff)
$magenta        = rgba(9141acff)
$cyan           = rgba(5bc8afff)

$highlight_low  = rgba(101010ff)
$highlight_med  = rgba(1c1c1cff)
$highlight_high = rgba(282828ff)

$border         = rgba(282828ff)

$selection_bg   = rgba(1c1c1cff)
$selection_fg   = rgba(dedddaff)
