# Adwaita darker
set -g @base            "#000000"
set -g @surface         "#101010"
set -g @overlay         "#1c1c1c"

set -g @muted           "#9a9996"
set -g @subtle          "#c0bfbc"
set -g @text            "#deddda"

set -g @accent          "#62a0ea"

set -g @red             "#ed333b"
set -g @green           "#57e389"
set -g @orange          "#ff7800"
set -g @yellow          "#ffa348"
set -g @blue            "#62a0ea"
set -g @magenta         "#9141ac"
set -g @cyan            "#5bc8af"

set -g @highlight_low   "#101010"
set -g @highlight_med   "#1c1c1c"
set -g @highlight_high  "#282828"

set -g @border          "#282828"

set -g @selection_bg    "#1c1c1c"
set -g @selection_fg    "#deddda"
