source "$REPO_INSTALL/desktop/audio.sh"
source "$REPO_INSTALL/desktop/bluetooth.sh"
source "$REPO_INSTALL/desktop/fonts.sh"
source "$REPO_INSTALL/desktop/hyprdeps.sh"
source "$REPO_INSTALL/desktop/user_environment.sh"
