# Hyprland config!

# Defaults for sokratOS:
# source = ~/.config/sokratOS/matugen/hypr/colors.conf
source = ~/.config/sokratOS/current/theme/hcolors.conf
source = ~/.config/hypr/configs/monitors.conf
source = ~/.config/hypr/configs/envs.conf
source = ~/.config/hypr/configs/autostart.conf
source = ~/.config/hypr/configs/looknfeel.conf
source = ~/.config/hypr/configs/windowrules.conf
source = ~/.config/hypr/configs/input.conf
source = ~/.config/hypr/configs/hyprutils.conf
source = ~/.config/hypr/configs/tiling.conf
source = ~/.config/hypr/configs/bindings.conf

exec-once = hyprctl dispatch workspace 1
