vim.keymap.set("n", "<leader>x", function()
  vim.cmd("update")
  vim.cmd("belowright split | resize 12")
  vim.cmd("terminal Rscript " .. vim.fn.shellescape(vim.fn.expand("%")))
	vim.cmd("startinsert")
end, { buffer = true, desc = "Run current R file with Rscript" })
