# vim:ft=kitty
## name: Crimson Rose (dark red UI + muted rose-pine accents)

foreground              #bebebe
background              #121212
selection_foreground    #121212
selection_background    #333333

url_color #7fb0b8

active_border_color     #595959
inactive_border_color   #595959
bell_border_color       #595959

active_tab_foreground   #bebebe
active_tab_background   #121212
inactive_tab_foreground #bebebe
inactive_tab_background #121212
tab_bar_background      #bebebe

# black
color0  #333333
color8  #8d85a6

# red
color1  #d16a85
color9  #e07a96

# green
color2  #2f6b7f
color10 #357b92

# yellow
color3  #d5ab6b
color11 #e2bd7a

# blue
color4  #7fb0b8
color12 #8fc3cb

# magenta
color5  #b194d1
color13 #c0a4e0

# cyan (warm “rose” accent, intentionally not neon)
color6  #d8aba9
color14 #e3b8b6

# white
color7  #bebebe
color15 #f4f0ff
