# Crimson Rose
$base           = rgba(0f0406ff)
$surface        = rgba(18080bff)
$overlay        = rgba(231014ff)

$muted          = rgba(8d85a6ff)
$subtle         = rgba(b9b1d3ff)
$text           = rgba(e0def4ff)

$accent         = rgba(d16a85ff)

$red            = rgba(d16a85ff)
$green          = rgba(2f6b7fff)
$yellow         = rgba(d5ab6bff)
$blue           = rgba(7fb0b8ff)
$magenta        = rgba(b194d1ff)
$cyan           = rgba(8fc3cbff)
$orange         = rgba(d8aba9ff)

$highlight_low  = rgba(18080bff)
$highlight_med  = rgba(231014ff)
$highlight_high = rgba(2f161cff)

$border         = rgba(351a20ff)

$selection_bg   = rgba(231014ff)
$selection_fg   = rgba(e0def4ff)
