# Crimson Rose
$base           = rgba(121212ff)
$surface        = rgba(333333ff)
$overlay        = rgba(595959ff)

$muted          = rgba(8d85a6ff)
$subtle         = rgba(b9b1d3ff)
$text           = rgba(e0def4ff)

$accent         = rgba(d16a85ff)

$red            = rgba(d16a85ff)
$green          = rgba(2f6b7fff)
$yellow         = rgba(d5ab6bff)
$blue           = rgba(7fb0b8ff)
$magenta        = rgba(b194d1ff)
$cyan           = rgba(8fc3cbff)
$orange         = rgba(d8aba9ff)

$highlight_low  = rgba(333333ff)
$highlight_med  = rgba(404040ff)
$highlight_high = rgba(595959ff)

$border         = rgba(282828ff)

$selection_bg   = rgba(1c1c1cff)
$selection_fg   = rgba(dedddaff)
