# Crimson Rose
set -g @base            "#121212"
set -g @surface         "#333333"
set -g @overlay         "#595959"

set -g @muted           "#8d85a6"
set -g @subtle          "#b9b1d3"
set -g @text            "#e0def4"

set -g @accent          "#d16a85"

set -g @red             "#d16a85"
set -g @green           "#2f6b7f"
set -g @yellow          "#d5ab6b"
set -g @blue            "#7fb0b8"
set -g @magenta         "#b194d1"
set -g @cyan            "#8fc3cb"
set -g @orange          "#d8aba9"

set -g @highlight_low   "#333333"
set -g @highlight_med   "#404040"
set -g @highlight_high  "#595959"

set -g @border          "#282828"

set -g @selection_bg    "#333333"
set -g @selection_fg    "#121212"
