# Crimson Rose

set -g @base            "#0f0406"
set -g @surface         "#18080b"
set -g @overlay         "#231014"

set -g @muted           "#8d85a6"
set -g @subtle          "#b9b1d3"
set -g @text            "#e0def4"

set -g @accent          "#d16a85"

set -g @red             "#d16a85"
set -g @green           "#2f6b7f"
set -g @yellow          "#d5ab6b"
set -g @blue            "#7fb0b8"
set -g @magenta         "#b194d1"
set -g @cyan            "#8fc3cb"
set -g @orange          "#d8aba9"

set -g @highlight_low   "#18080b"
set -g @highlight_med   "#231014"
set -g @highlight_high  "#2f161c"

set -g @border          "#351a20"

set -g @selection_bg    "#231014"
set -g @selection_fg    "#e0def4"
