# Hyprland config!

# Edit the following files with discretion!:
source = ~/.config/sokratOS/matugen/hypr/colors.conf
source = ~/.config/hypr/configs/envs.conf
source = ~/.config/hypr/configs/autostart.conf
source = ~/.config/hypr/configs/styles/sharp.conf
source = ~/.config/hypr/configs/windowrules.conf
source = ~/.config/hypr/configs/input.conf
source = ~/.config/hypr/configs/hyprutils.conf
source = ~/.config/hypr/configs/tiling.conf
source = ~/.config/hypr/configs/bindings.conf

# Edit your own monitor settings!
source = ~/.config/hypr/configs/monitors.conf
